country_info = {
    "Afghanistan": {"country_code": "af", "currency_code": "AFN"},
    "Albania": {"country_code": "al", "currency_code": "ALL"},
    "Algeria": {"country_code": "dz", "currency_code": "DZD"},
    "American Samoa": {"country_code": "as", "currency_code": "USD"},
    "Andorra": {"country_code": "ad", "currency_code": "EUR"},
    "Angola": {"country_code": "ao", "currency_code": "AOA"},
    "Anguilla": {"country_code": "ai", "currency_code": "XCD"},
    "Antarctica": {"country_code": "aq", "currency_code": None},
    "Antigua and Barbuda": {"country_code": "ag", "currency_code": "XCD"},
    "Argentina": {"country_code": "ar", "currency_code": "ARS"},
    "Armenia": {"country_code": "am", "currency_code": "AMD"},
    "Aruba": {"country_code": "aw", "currency_code": "AWG"},
    "Australia": {"country_code": "au", "currency_code": "AUD"},
    "Austria": {"country_code": "at", "currency_code": "EUR"},
    "Azerbaijan": {"country_code": "az", "currency_code": "AZN"},
    "Bahamas": {"country_code": "bs", "currency_code": "BSD"},
    "Bahrain": {"country_code": "bh", "currency_code": "BHD"},
    "Bangladesh": {"country_code": "bd", "currency_code": "BDT"},
    "Barbados": {"country_code": "bb", "currency_code": "BBD"},
    "Belarus": {"country_code": "by", "currency_code": "BYN"},
    "Belgium": {"country_code": "be", "currency_code": "EUR"},
    "Belize": {"country_code": "bz", "currency_code": "BZD"},
    "Benin": {"country_code": "bj", "currency_code": "XOF"},
    "Bermuda": {"country_code": "bm", "currency_code": "BMD"},
    "Bhutan": {"country_code": "bt", "currency_code": "BTN"},
    "Bolivia": {"country_code": "bo", "currency_code": "BOB"},
    "Bosnia and Herzegovina": {"country_code": "ba", "currency_code": "BAM"},
    "Botswana": {"country_code": "bw", "currency_code": "BWP"},
    "Brazil": {"country_code": "br", "currency_code": "BRL"},
    "Brunei Darussalam": {"country_code": "bn", "currency_code": "BND"},
    "Bulgaria": {"country_code": "bg", "currency_code": "BGN"},
    "Cambodia": {"country_code": "kh", "currency_code": "KHR"},
    "Cameroon": {"country_code": "cm", "currency_code": "XAF"},
    "Canada": {"country_code": "ca", "currency_code": "CAD"},
    "Chile": {"country_code": "cl", "currency_code": "CLP"},
    "China": {"country_code": "cn", "currency_code": "CNY"},
    "Colombia": {"country_code": "co", "currency_code": "COP"},
    "Costa Rica": {"country_code": "cr", "currency_code": "CRC"},
    "Croatia": {"country_code": "hr", "currency_code": "EUR"},
    "Cuba": {"country_code": "cu", "currency_code": "CUP"},
    "Cyprus": {"country_code": "cy", "currency_code": "EUR"},
    "Czech Republic": {"country_code": "cz", "currency_code": "CZK"},
    "Denmark": {"country_code": "dk", "currency_code": "DKK"},
    "Dominican Republic": {"country_code": "do", "currency_code": "DOP"},
    "Ecuador": {"country_code": "ec", "currency_code": "USD"},
    "Egypt": {"country_code": "eg", "currency_code": "EGP"},
    "Estonia": {"country_code": "ee", "currency_code": "EUR"},
    "Finland": {"country_code": "fi", "currency_code": "EUR"},
    "France": {"country_code": "fr", "currency_code": "EUR"},
    "Germany": {"country_code": "de", "currency_code": "EUR"},
    "Greece": {"country_code": "gr", "currency_code": "EUR"},
    "Hong Kong": {"country_code": "hk", "currency_code": "HKD"},
    "Hungary": {"country_code": "hu", "currency_code": "HUF"},
    "Iceland": {"country_code": "is", "currency_code": "ISK"},
    "India": {"country_code": "in", "currency_code": "INR"},
    "Indonesia": {"country_code": "id", "currency_code": "IDR"},
    "Iran, Islamic Republic of": {"country_code": "ir", "currency_code": "IRR"},
    "Ireland": {"country_code": "ie", "currency_code": "EUR"},
    "Israel": {"country_code": "il", "currency_code": "ILS"},
    "Italy": {"country_code": "it", "currency_code": "EUR"},
    "Japan": {"country_code": "jp", "currency_code": "JPY"},
    "Kenya": {"country_code": "ke", "currency_code": "KES"},
    "Korea, Republic of": {"country_code": "kr", "currency_code": "KRW"},
    "Malaysia": {"country_code": "my", "currency_code": "MYR"},
    "Mexico": {"country_code": "mx", "currency_code": "MXN"},
    "Netherlands": {"country_code": "nl", "currency_code": "EUR"},
    "New Zealand": {"country_code": "nz", "currency_code": "NZD"},
    "Nigeria": {"country_code": "ng", "currency_code": "NGN"},
    "Norway": {"country_code": "no", "currency_code": "NOK"},
    "Pakistan": {"country_code": "pk", "currency_code": "PKR"},
    "Philippines": {"country_code": "ph", "currency_code": "PHP"},
    "Poland": {"country_code": "pl", "currency_code": "PLN"},
    "Portugal": {"country_code": "pt", "currency_code": "EUR"},
    "Romania": {"country_code": "ro", "currency_code": "RON"},
    "Russian Federation": {"country_code": "ru", "currency_code": "RUB"},
    "Saudi Arabia": {"country_code": "sa", "currency_code": "SAR"},
    "Singapore": {"country_code": "sg", "currency_code": "SGD"},
    "South Africa": {"country_code": "za", "currency_code": "ZAR"},
    "Spain": {"country_code": "es", "currency_code": "EUR"},
    "Sweden": {"country_code": "se", "currency_code": "SEK"},
    "Switzerland": {"country_code": "ch", "currency_code": "CHF"},
    "Thailand": {"country_code": "th", "currency_code": "THB"},
    "Turkiye": {"country_code": "tr", "currency_code": "TRY"},
    "Ukraine": {"country_code": "ua", "currency_code": "UAH"},
    "United Arab Emirates": {"country_code": "ae", "currency_code": "AED"},
    "United Kingdom": {"country_code": "gb", "currency_code": "GBP"},
    "United States": {"country_code": "us", "currency_code": "USD"},
    "Vietnam": {"country_code": "vn", "currency_code": "VND"},
    "Zimbabwe": {"country_code": "zw", "currency_code": "ZWL"},
}
